













##########################################Test Code#######################################
query = "AAAAGATTGGCATCTTAGATTAATTTTTTTTTTTTTCAAGCAGAAGACGGCATACGAGATCGAGTAATGTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTTCGTCTGATCTCGGAAGCTAAGCAGGGTCGGGCCTGGTTAGTACTTGGATGGGAGACCGCCTGGGAATACCGGGTGCTGTAGGCTT"
blastEntry = "2	AP001524.1-201|miRNA	100.000	53	0	0	106	158	6	58	7.54e-021	99.0"
dbSeq = "TCTCATCTGATCTCGGAAGCTAAGCAGGGTCGGGCCTGGTTAGTACTTGGATGGGAGAAATT"

print(len(query))
print(len(dbSeq))
print(query[105:158])
print(dbSeq[5:58])